
package acme.service.soap.hotelws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-07-14T15:15:34.091+01:00
 * Generated source version: 2.6.6-redhat-3
 */

@SuppressWarnings("serial")
@WebFault(name = "DataBaseException", targetNamespace = "http://soap.service.acme/HotelWS/")
public class DataBaseException_Exception extends Exception {
    
    private acme.service.soap.hotelws.DataBaseException dataBaseException;

    public DataBaseException_Exception() {
        super();
    }
    
    public DataBaseException_Exception(String message) {
        super(message);
    }
    
    public DataBaseException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DataBaseException_Exception(String message, acme.service.soap.hotelws.DataBaseException dataBaseException) {
        super(message);
        this.dataBaseException = dataBaseException;
    }

    public DataBaseException_Exception(String message, acme.service.soap.hotelws.DataBaseException dataBaseException, Throwable cause) {
        super(message, cause);
        this.dataBaseException = dataBaseException;
    }

    public acme.service.soap.hotelws.DataBaseException getFaultInfo() {
        return this.dataBaseException;
    }
}
