
package com.jboss.soap.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * Sun Jun 29 22:49:51 BST 2014
 * Generated source version: 2.6.6-redhat-3
 */

@XmlRootElement(name = "listAvailablePlanes", namespace = "http://service.soap.jboss.com/AcmeDemo/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listAvailablePlanes", namespace = "http://service.soap.jboss.com/AcmeDemo/")

public class ListAvailablePlanes {

    @XmlElement(name = "in")
    private com.jboss.soap.service.FlightRequest in;

    public com.jboss.soap.service.FlightRequest getIn() {
        return this.in;
    }

    public void setIn(com.jboss.soap.service.FlightRequest newIn)  {
        this.in = newIn;
    }

}

