package com.jboss.soap.service.acmedemo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-09-30T16:22:26.015+01:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", name = "AcmeDemoInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface AcmeDemoInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listAvailablePlanes", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.ListAvailablePlanes")
    @WebMethod(action = "http://service.soap.jboss.com/AcmeDemo/listAvailablePlanes")
    @ResponseWrapper(localName = "listAvailablePlanesResponse", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.ListAvailablePlanesResponse")
    public java.util.List<com.jboss.soap.service.acmedemo.Flight> listAvailablePlanes(
        @WebParam(name = "in", targetNamespace = "")
        com.jboss.soap.service.acmedemo.FlightRequest in
    );
}
