//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 11:25:50 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.soap.jboss.com/AcmeDemo/")
package com.jboss.soap.service.acmedemo;
