
package com.jboss.soap.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * Thu Jul 17 14:09:14 BST 2014
 * Generated source version: 2.6.6-redhat-3
 */

@XmlRootElement(name = "DataBaseException", namespace = "http://exception.service.soap.jboss.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataBaseException", namespace = "http://exception.service.soap.jboss.com/")

public class DataBaseExceptionBean {

    private java.lang.String message;

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

